export const contactUsEmailTemplate = (
  name: string,
  mobileNo: string,
  email: string,
  message: string
) => {
  return `
<!DOCTYPE html>
<html>
<head>
    <title>Contact us Message</title>
</head>
<body>
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: auto;">
        <h2 style="color: #333;text-align: center;">Contact Us!</h2>
         <p style="font-size: 16px; color: #444;">New Message from ${name} ${mobileNo} (${email})</p>
        <p style="font-size: 16px; color: #444;margin-bottom:10px">
            ${message}
        </p>
        <p style="font-size: 16px; color: #444;">
            Email generated by Webease.
        </p>
    </div>
</body>
</html>`;
};
